### ISSUE TITLE
อาจารย์ครับสอบถามเรื่อง web ครับ

### ISSUE THREAD

**Issue by thakdanai2017** [ballweera/swt-contact-list#2]
web ที่ิอาจารย์ให้ มา ไม่มี id เลยอ่ะครับ ผมอ้างอิงจากอะไรได้บ้างถึงจะเข้าไปกรอกข้อมูลใน ช่องนั้น ๆ ได้
อย่างเช่น ถ้าจะเพิ่ม contact ก็ต้องกด add ก่อน แต่ผมไม่ทราบว่า ต้องใช้ อะไรในการอ้างไปถึง addอ่ะครับ

รบกวนด้วยครับ

**Comment by ballweera** [comment]
งานนี้ให้โฟกัสที่การเขียนเทส ไม่ต้องกังวลกับหน้าเว็บนะครับ
